# site settings
title: Adrien Gauvry
subtitle: 
email: adrien.gauvry@gmail.com
description: Je m'appelle Adrien Gauvry, je suis actuellement étudiant en informatique. C'est en particulier le web qui me passionne et je souhaite vous faire passer cette passion à travers ce site.

baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 0666081989

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/adriengauvry
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
